# ---------------------------------------------------------------------------
# script.py
# Created on: Fri Aug 31 2012 09:38:59 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Check out any necessary licenses
print("Check out Spatial Analyst extension")
gp.CheckOutExtension("spatial")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx")
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Conversion Tools.tbx")

print("Processing: BattleGovernmentRegainsTerritory")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\BattleGovernmentRegainsTerritory.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_BattleGovernmentRegainsTerritory.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_BattleGovernmentRegainsTerritory_EucDist.img"
Output_direction_raster = ""
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: BattleNoChangeOfTerritory")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\BattleNoChangeOfTerritory.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_BattleNoChangeOfTerritory.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_BattleNoChangeOfTerritory_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: BattleRebelsOvertakeTerritory")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\BattleRebelsOvertakeTerritory.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_BattleRebelsOvertakeTerritory.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_BattleRebelsOvertakeTerritory_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: HeadquartersOrBaseEstablished")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\HeadquartersOrBaseEstablished.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_HeadquartersOrBaseEstablished.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_HeadquartersOrBaseEstablished_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: NonViolentActivityByAConflictActor")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\NonViolentActivityByAConflictActor.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_NonViolentActivityByAConflictActor.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_NonViolentActivityByAConflictActor_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: RiotersDRC")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\RiotersDRC.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_RiotersDRC.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_RiotersDRC_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: RiotsProtests")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\RiotsProtests.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_RiotsProtests.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_RiotsProtests_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: ViolenceAgainstCiviliance")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\ViolenceAgainstCiviliance.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_ViolenceAgainstCiviliance.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_ViolenceAgainstCiviliance_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################

print("Processing: NonViolentTransferOfTerritory")
# Local variables...
huntingDomain = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\Shp\\NonViolentTransferOfTerritory.shp"
extent_tif = "F:\\DataF\\mbaumann\\Congo\\tmp\\extent.tif"
DRC_Protectedareas_Projected_HuntingDomain_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_NonViolentTransferOfTerritory.img"
DRC_Protectedareas_Projected_HuntingDomain_EucDist_img = "F:\\DataF\\mbaumann\\Congo\\tmp\\Routes\\raster\\DRC_ConflictData_Projected_NonViolentTransferOfTerritory_EucDist.img"
print("Set output Extent")
# gp.Extent = extent_tif
# Process: Polygon to Raster...
print("Polygon to raster")
gp.PointToRaster_conversion(huntingDomain, "EVENT_TYPE", DRC_Protectedareas_Projected_HuntingDomain_img, "MEAN", "NONE", "60")
print("Euclidean Distance")
# Process: Euclidean Distance...
gp.EucDistance_sa(DRC_Protectedareas_Projected_HuntingDomain_img, DRC_Protectedareas_Projected_HuntingDomain_EucDist_img, "", "60", Output_direction_raster)
#####################################################################################